import { profile } from '@/lib/profile';
import { Icon } from './Icon';
export default function Projects() {
  return <section className="section container" id="proyectos"><div className="section-heading"><h2>Ideas en marcha.<br /><span className="muted">Proyectos con dirección.</span></h2><a className="text-link" href={profile.github} target="_blank" rel="noopener noreferrer">Visitar mi GitHub <Icon name="arrow" /></a></div>
    <div className="projects-grid"><article className="project project-nubo"><div className="nubo-scene" aria-hidden="true"><div className="nubo-ring ring-a" /><div className="nubo-ring ring-b" /><div className="nubo-core">n<span>.</span></div><span className="scene-bottom">NUBO / CONCEPTO VISUAL</span></div><div className="project-body"><span className="status"><span className="tiny-dot" /> En desarrollo</span><h3>Nubo <Icon name="spark" /></h3><p>Proyecto personal con Python e inteligencia artificial. Su alcance e implementación están en desarrollo; todavía no hay una demostración pública.</p><ul className="tags"><li>Python</li><li>Inteligencia artificial</li></ul></div></article>
    <article className="project project-planned"><div className="project-body"><span className="status planned">Planificado</span><h3>Ventas e inventario <Icon name="code" /></h3><p>Un sistema con Java para productos, ventas e inventario, conectado con mi experiencia en logística. El desarrollo aún no ha comenzado.</p><ul className="tags"><li>Java</li><li>Procesos operativos</li></ul><div className="project-scope"><span>Alcance previsto</span><p>Catálogo de productos<br />Registro de ventas<br />Control de existencias</p></div></div></article></div>
    <p className="project-note">Las demostraciones y el código se incorporarán cuando estén disponibles. Las piezas visuales presentan conceptos, no productos terminados.</p>
  </section>;
}
