import { MotionWords } from './ProgrammerEffects';
import { pythonExample } from '@/lib/profile';
const chapters = [
  { word: 'Python.', title: 'Datos que toman forma.', body: 'Python es mi prioridad técnica actual. Mi dirección: transformar datos y reducir tareas repetitivas con software.', tags: ['Python', 'Procesamiento de datos'], state: 'En desarrollo técnico' },
  { word: 'Web.', title: 'Una idea, una interfaz.', body: 'Mi base en HTML, CSS y JavaScript se orienta a interfaces claras y adaptables. La IA puede apoyar el proceso de desarrollo; el resultado siempre necesita revisión.', tags: ['HTML', 'CSS', 'JavaScript'], state: 'Base actual' },
  { word: 'IA.', title: 'Contexto para responder.', body: 'Integraciones de modelos y asistentes que consulten documentos mediante RAG. Una línea futura de trabajo, todavía sin implementaciones públicas.', tags: ['Integraciones de IA', 'RAG'], state: 'Dirección futura' },
];
export default function ServicesGrid() {
  return <section id="conocimientos" className="section container technical"><div className="section-heading"><h2><MotionWords text="Del código" /><br /><span className="mint"><MotionWords text="a lo que hace posible." /></span></h2><p>Tres líneas de trabajo.<br />Una dirección técnica definida.</p></div><div className="tech-story"><div className="tech-stage" data-active="0"><div className="stage-route" aria-hidden="true"><span>Datos</span><i /><span>Lógica</span><i /><span>Aplicación</span></div><div className="live-terminal"><div className="live-terminal-title"><span>procesar_datos.py</span><small>Ejemplo ilustrativo</small></div><pre aria-label="Ejemplo de Python: contar registros por estado"><code data-live-code aria-hidden="true">{pythonExample}</code></pre><div className="terminal-foot"><span aria-hidden="true">●</span><span data-stage-label>Python · Datos y lógica</span></div></div><p className="stage-note">El código muestra una función de ejemplo, no una implementación de los proyectos del portafolio.</p><div className="stage-orbit" aria-hidden="true"><span>0</span><span>1</span><span>0</span><span>1</span></div></div><div className="tech-chapters">{chapters.map((chapter,i)=><article className="tech-chapter" data-chapter={i} key={chapter.word}><span className="chapter-word" aria-hidden="true">{chapter.word}</span><h3><MotionWords text={chapter.title} /></h3><p>{chapter.body}</p><ul className="tags">{chapter.tags.map(t=><li key={t}>{t}</li>)}</ul><span className="chapter-state">{chapter.state}</span></article>)}</div></div><div className="linux-note"><p>Entorno y conocimientos complementarios</p><span>Linux · Ubuntu · Omarchy · Java</span></div></section>;
}
